ns.CONST = {
//IMG_LOADER : "imgLoader" //SELECTOR CLASS

	TEMPLATES_DEFAULT: "MVC_TEMPLATES"
,	TEMPLATE_SET : "TEMPLATE_SET" //SELECTOR CLASS
, TEMPLATE_NODE_TAG : "TEXTAREA"
, TEMPLATE_DEFAULT : "TEMPLATE_DEFAULT"
	
, VIEW_CLASS : "VIEW"

, MODEL_DEFAULT_ID : "id"
	
, NODE_TYPE_DEFAULT : "DIV"
, IMAGE_LOADER_CLASS : "IMG_LOADER"
		
, EVENTS : {
		SHOW: "SHOW"
	, PREP: "PREP"
	, HIDE: "HIDE"
	, REFRESH: "REFRESH"
	, LOAD: "LOAD"
	
	, DIRTY: "DIRTY"
	, CLEAN: "CLEAN"
	
	, CHANGE: "CHANGE"
	}	
};