ns.CONST = {
//IMG_LOADER : "imgLoader" //SELECTOR CLASS

	VIEWS_DEFAULT: "MVC_VIEWS"
,	VIEW_SET : "VIEW_SET" //SELECTOR CLASS
, VIEW_NODE_TAG : "TEXTAREA"
, VIEW_DEFAULT : "VIEW_DEFAULT"
, VIEW_CLASS : "VIEW"

, MODEL_DEFAULT_ID : "id"
	
, NODE_TYPE_DEFAULT : "DIV"
, IMAGE_LOADER_CLASS : "IMG_LOADER"
		
, EVENTS : {
		SHOW: "SHOW"
	, PREP: "PREP"
	, HIDE: "HIDE"
	, REFRESH: "REFRESH"
	, LOAD: "LOAD"
	
	, DIRTY: "DIRTY"
	, CLEAN: "CLEAN"
	
	, CHANGE: "CHANGE"
	}	
};