
var ns=mvc={};ns.NAME="mvc";root=ns;ns.CONST={VIEWS_DEFAULT:"MVC_VIEWS",VIEW_SET:"VIEW_SET",VIEW_NODE_TAG:"TEXTAREA",VIEW_DEFAULT:"VIEW_DEFAULT",VIEW_CLASS:"VIEW",MODEL_DEFAULT_ID:"id",NODE_TYPE_DEFAULT:"DIV",IMAGE_LOADER_CLASS:"IMG_LOADER",EVENTS:{SHOW:"SHOW",PREP:"PREP",HIDE:"HIDE",REFRESH:"REFRESH",LOAD:"LOAD",DIRTY:"DIRTY",CLEAN:"CLEAN",CHANGE:"CHANGE"}};ns.Controller=(function(){var _ns=ns,_instances=0;var Template=(function(){function _gsub(str,pattern,replacement){var result='',source=str,match;replacement=_prepareReplacement(replacement);while(source.length>0){if(match=source.match(pattern)){result+=source.slice(0,match.index);result+=(replacement(match))||'';source=source.slice(match.index+match[0].length);}else{result+=source,source='';}}
return result;}
function _prepareReplacement(replacement){if(typeof(replacement)==="function"){return replacement;}
var template=new View(replacement);return function(match){return template.evaluate(match);};}
function _load(data,views,templateName,parentData,iterator){var _finalObj=data,_parsed,_template=views[templateName],_parentData=parentData||{},_myData={};if(typeof(iterator)!=="undefined")_finalObj.iterator=iterator;function _handleArray(arry,newTemplateName){var _returnList="";if(views[newTemplateName]){for(var i=0;i<arry.length;i++){var _returnObj=_load(arry[i],views,newTemplateName,arry,i+1);_returnList+=_returnObj;}}
return _returnList;}
if(_finalObj instanceof Array){_parsed=_handleArray(_finalObj,templateName);return(_parsed);}else{for(var attrib in _finalObj){if(_finalObj.hasOwnProperty(attrib)){if(_finalObj[attrib]instanceof Array){_finalObj[attrib]=_handleArray(_finalObj[attrib],attrib);}else if(_finalObj[attrib]instanceof Object){if(views[attrib]){var _returnObj=_load(_finalObj[attrib],views,attrib,_finalObj,null);_finalObj[attrib]=_returnObj;}}}}
return(_template&&_template.evaluate)?_template.evaluate(_finalObj):"";}}
function _Template(params){this._view=(params&&(typeof(params.view)!=="undefined"))?params.view:"";this._name=(params&&(typeof(params.name)!=="undefined"))?params.name:"";this._pattern=(params&&(typeof(params.pattern)!=="undefined"))?params.pattern:/(^|.|\r|\n)(#\{(.*?)\})/;this._template;this._children={};this._childrenInitialzed=false;this._setTemplate=function(templateStr,name){var _lookupname=name||(this._name!="")?this._name:_ns.CONST.VIEW_DEFAULT;this._template=templateStr.toString();this._children[_lookupname]=this;};if((params)&&(typeof(params.template)!=="undefined")){this._setTemplate(params.template);}
return this;}
_Template.prototype.addChild=function(view){this._children[view.name()]=view;};_Template.prototype.children=function(){if(this._childrenInitialzed)return this._children;var _tplContainer=document.getElementById(this._view),_templateNodes=(_tplContainer)?_tplContainer.getElementsByTagName(_ns.CONST.VIEW_NODE_TAG):[];for(var i=0,len=_templateNodes.length;i<len;i++){var _tplNode=_templateNodes[i];if(_tplNode.className==this._name){this._setTemplate(_tplNode.value);}else{this.addChild(new _Template({template:_tplNode.value,name:_tplNode.className}));}}
this._childrenInitialzed=true;return this._children;};_Template.prototype.setPattern=function(pattern){this._pattern=pattern;};_Template.prototype.evaluate=function(object){if((typeof(object)!=="undefined")&&(typeof(object.get)==="function")){object=object.get();}
var _output=this._template;for(attrib in object){_output=_output.replace(eval("/#\{"+attrib+"\}/g"),object[attrib]);}
return _output;return _gsub(this._template,this._pattern,function(match){if(object==null)return'';var before=match[1]||'';if(before=='\\')return match[2];var ctx=object,expr=match[3];var pattern=/^([^.[]+|\[((?:.*?[^\\])?)\])(\.|\[|$)/;match=pattern.exec(expr);if(match==null)return before;while(match!=null){var comp=(match[1].indexOf('[')===0)?_gsub(match[2],'\\\\]',']'):match[1];ctx=ctx[comp];if(null==ctx||''==match[3])break;expr=expr.substring('['==match[3]?match[1].length:match[0].length);match=pattern.exec(expr);}
var _ctx=ctx||'';return before+_ctx;});};_Template.prototype.load=function(data){return _load(data,this.children(),_ns.CONST.VIEW_DEFAULT);};_Template.prototype.name=function(str){if(this._name!=""){return this._name;}
this._name=str;};return _Template;})();function Controller(params){this._instance=_instances++;this._parent=(params&&params.parent)?params.parent:false;this._children=(params&&params.children)?params.children:[];this._model=false;this._container=(params&&params.container)?params.container:false;this._useContainer=(params&&params.useContainer)?params.useContainer:false;this._staticContent=(params&&params.staticContent)?params.staticContent:false;this._tag=(params&&params.tag)?params.tag:_ns.CONST.NODE_TYPE_DEFAULT;this._prepped=false;this._visible=false;this._template=false;this._node=false;this._container=(params&&params.container)?params.container:false;this._pattern=((params)&&(typeof(params.pattern)!=="undefined"))?params.pattern:/(^|.|\r|\n)(#\{(.*?)\})/;this.Model=_ns.Model;this.View=_ns.CONST.VIEWS_DEFAULT;utils.Evint.call(this,this._parent);utils.Laundry.apply(this);this.constructor=Controller;this._getTemplate=function(){if(this._template){return this._template;}
this._template=new Template({view:this.View,pattern:this._pattern});return this._template;};if(params&&params.model){this.model(params.model);}
return this;}
Controller.prototype.document=function(){return document;};Controller.prototype.idee=function(){return"_ns.Controller."+this._instance;};Controller.prototype.setParent=function(parent){if(this._parent){throw"I already have a parent!  You can't adopt me!";}
this._parent=parent;return this;};Controller.prototype.getParent=function(){return this._parent;};Controller.prototype.addChild=function(child){this._children.push(child);return this;};Controller.prototype.removeChild=function(unwanted){this._children=this._children.filter(function(child){return child!=unwanted;});return this;};Controller.prototype.isPrepped=function(){return this._prepped;};Controller.prototype.setPrepped=function(state){this._prepped=state;};Controller.prototype.isVisible=function(){return this._visible;};Controller.prototype.setVisible=function(){this._visible=true;};Controller.prototype.setNotVisible=function(){this._visible=false;};Controller.prototype.prepare=function(){if(!this._prepped){this.node();this.setPrepped(true);this.fire(_ns.CONST.EVENTS.PREP);}
this._children.forEach(function(controller){controller.prepare();});return this;};Controller.prototype.refresh=function(){if(!this._prepped)this.prepare();var _data=this.model();if(!this._staticContent){if((typeof(this.model())!=="undefined")&&(typeof(this.model().get)==="function")){_data=this.model().get();}
this.node().innerHTML=this._getTemplate().load(_data);var _imagesToLoad=this.node().select("img."+_ns.CONST.IMAGE_LOADER_CLASS);for(var i=0,len=_imagesToLoad.length;i<len;i++){new utils.imageLoader(_imagesToLoad[i]);}}
this.isClean();this.fire(_ns.CONST.EVENTS.REFRESH);this.load();this._children.forEach(function(controller){controller.refresh();});return this;};Controller.prototype.load=function(){};Controller.prototype.show=function(){if(!this.isVisible()){if(!this._prepped){this.prepare();}
if(this.needWashing()){this.refresh();}
this.node().style.display="";this.setVisible();this.fire(_ns.CONST.EVENTS.SHOW);}
this._children.forEach(function(controller){controller.show();});return this;};Controller.prototype.hide=function(){if(!this._prepped){return this;}
if(this._visible){this.node().style.display="none";this.setNotVisible();this.fire(_ns.CONST.EVENTS.HIDE);}
this._children.forEach(function(controller){controller.hide();});return this;};Controller.prototype.toggle=function(){if(this._visible){_action=this.hide();}else{_action=this.show();}
return this;};Controller.prototype.model=function(model){if(this._model&&(typeof(model)=="undefined")){return this._model;}
else{try{this._model=model||new this.Model();this._model.subscribe(_ns.CONST.EVENTS.CHANGE,this.isDirty,utils.Evint.CONST.PRIORITY_FIRST);return this._model;}catch(err){debug.error(err,this,this.idee());}}};Controller.prototype.node=function(){if(this._node){return this._node;}
this._node=(this._useContainer)?this.container():this.document().createElement(this._tag);var _className=this.View.replace(/\./g,"_").toUpperCase()+" "+_ns.CONST.VIEW_CLASS;this._node.className=(this._node.className=="")?_className:this._node.className+" "+_className;this._node.style.display="none";if(!this._useContainer){this.container().appendChild(this._node);}
utils.sizzle.call(this._node);return this._node;};Controller.prototype.container=function(container){if(this._container){return this._container;}else{this._container=container||this.document().body;return this._container;}};Controller.getInstances=function(){return _instances;};return Controller;})();ns.Manager=(function(){var _ns=ns;function Manager(){utils.Evint.apply(this);var _this=this,_controllers=utils.Array();function _findById(idee){var _controller=_controllers.findFirst(function(controller){return(controller.idee()==idee);});return _controller;}
function _findByClass(Controller,isFamily,include){var _instances=[],_include=(include)?true:false;_controllers.forEach(function(controller){var _return=(!_include);if(_include){if(controller instanceof Controller){_return=_include;}}else{if(controller.constructor==Controller){_return=_include;}}
if(_return){_instances.push(controller);}});return _instances;}
function _register(instance){if(!instance instanceof _ns.Controller){throw"I don't know how to be your manager!  You don't work for me!";}
_controllers.push(instance);return instance;}
function _destroyById(idee){for(var i=0,len=_controllers.length;i<len;i++){if(_controllers[i].idee()==idee){_controllers.splice(i,1);i--;}}}
_this.register=function(controller){if(_findById(controller.idee())){return controller;}else{return _register(controller);}};_this.get=function(idee){return _findById(idee);};_this.getAll=function(){return _controllers.slice();};_this.getAllVisible=function(){var _returnArray=[];_controllers.forEach(function(controller){if(controller.isVisible()){_returnArray.push(controller);}});return _returnArray;};_this.create=function(Controller){if(!Controller instanceof _ns.Controller){throw"I don't know how to create something I can't manage!";}
return _register(new Controller());};_this.show=function(idee){var _controller=_findById(idee);if(!_controller){throw"How can I show that which does not exist?";}
_controller.show();};_this.showAll=function(){_controllers.forEach(function(controller){controller.show();});return _this;};_this.hide=function(idee){var _controller=_findById(idee);if(!_controller){throw"How can I hide something that is not even there?";}
_controller.hide();};_this.hideAll=function(){_controllers.forEach(function(controller){controller.hide();});return _this;};_this.hideAllByClass=function(Controller,isFamily){var _instances=_findByClass(Controller,isFamily);_instances.each(function(controller){controller.hide();});return _this;};_this.hideAllExceptTheseIds=function(ids){var _ids=(typeof(ids)!=="undefined")?ids:[];_controllers.forEach(function(controller){if(_ids.indexOf(controller.idee())==-1){controller.hide();}});};_this.hideAllExceptTheseClasses=function(Controllers,isFamily){var _excludeFindings=true,_instances=_findByClass(Controller,isFamily,_excludeFindings);_instances.forEach(function(controller){controller.hide();});return _this;};_this.destroy=function(idee){_destroyById(uniqueId);};return _this;}
return Manager;})();ns.Model=(function(){var _ns=ns,_root=root,_TYPES={STRING:"string",NUMBER:"number",BOOLEAN:"boolean",ARRAY:"array",FUNCTION:"function",OBJECT:"object",UNDEFINED:"undefined",NULL:"null"},_API=function()
{return{API:"API",GET:"get",SET:"set",ADD:"add",REMOVE:"remove",CHILDREN:"children",CHILD:"child",_VAL_:"_val_",_ATTRIBUTES_:"_attributes_",_PARENT_:"_parent_",_IS_SAFE_:"_isSafe_"};};function _typeof(val){var s=typeof val;if(s===_TYPES.OBJECT){if(val){if(typeof val.length===_TYPES.NUMBER&&!(val.propertyIsEnumerable('length'))&&typeof val.splice===_TYPES.FUNCTION){s=_TYPES.ARRAY;}}else{s=_TYPES.NULL;}}
return s;}
var _Children=(function(){function _Array(){var
_array=utils.Array.apply({},arguments),_this;;_array.setThis=function(scope){_this=scope;};_array.pop=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].pop.apply(_array,arguments);};_array.push=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].push.apply(_array,arguments);};_array.reverse=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].reverse.apply(_array,arguments);};_array.shift=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].shift.apply(_array,arguments);};_array.sort=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].sort.apply(_array,arguments);};_array.splice=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].splice.apply(_array,arguments);};_array.unshift=function(){_this.fire(_ns.CONST.EVENTS.CHANGE);return[].unshift.apply(_array,arguments);};return _array;}
return _Array;})();function _Model(initValue,parent){var _this=this;this._val_;this._attributes_=[];this._parent_=parent||false;utils.Evint.call(this,this._parent_);this.API=_API();if(typeof(initValue)!=="undefined"){this.set(initValue);}
return this;}
_Model.prototype._isSafe_=function(attributeId)
{var _protected=utils.Array(this.API,utils.Evint.API).arrayify();if(_protected.indexOf(attributeId)==-1){return true;}
return false;};_Model.prototype.set=function(value)
{switch(_typeof(value)){case _TYPES.ARRAY:this._val_=_Children(value.map(function(item)
{return new _Model(item);}));this._val_.setThis(this);this.fire(_ns.CONST.EVENTS.CHANGE);return true;break;case _TYPES.OBJECT:var _obj=new _Model();for(var attrib in this){if((this.hasOwnProperty(attrib))&&(this._isSafe_(attrib))&&(!(value[attrib]))){this.remove(attrib);}}
if(value instanceof _Model){this._val_=_obj;this.fire(_ns.CONST.EVENTS.CHANGE);return true;}else{for(var attrib in value){if(value.hasOwnProperty(attrib)){if(this._isSafe_(attrib)){if(this[attrib]){try{this[attrib].set(value[attrib]);}catch(err){debug.error(attrib,this,"failed!",err);}}else{var _value;if(value[attrib]instanceof _Model){_value=value[attrib];}else{_value=new _Model(value[attrib]);}
_obj.add(attrib,_value);this.add(attrib,_obj[attrib]);}}else{}}}
this._val_=_obj;this.fire(_ns.CONST.EVENTS.CHANGE);return true;}
break;default:this._val_=value;this.fire(_ns.CONST.EVENTS.CHANGE);return true;break;}
return false;};_Model.prototype.get=function(){switch(_typeof(this._val_)){case _TYPES.ARRAY:return this._val_.map(function(item){return item.get();});break;default:if(this._val_ instanceof _Model){var _return={};this._attributes_.forEach(function(item){_return[item]=this[item].get();},this);return _return;}
return this._val_;break;}};_Model.prototype.add=function(attributeId,child)
{var _child=(child instanceof _Model)?child:new _Model(child);if(_typeof(this._val_)!=_TYPES.ARRAY){if(this._isSafe_(attributeId)){if(this._attributes_.indexOf(attributeId)==-1){this._attributes_.push(attributeId);}
this[attributeId]=_child;this.fire(_ns.CONST.EVENTS.CHANGE);return true;}
return false;}else{this._val_.push(_child);}};_Model.prototype.remove=function(attributeId){var
_attribute;if((this._isSafe_(attributeId))&&(_typeof(this[attributeId])!=_TYPES.UNDEFINED)){_attribute=this[attributeId];if(delete this[attributeId]){this._attributes_=this._attributes_.filter(function(item){return item!=attributeId;});this.fire(_ns.CONST.EVENTS.CHANGE);return _attribute;}else{return false;}}
return _attribute;};_Model.prototype.children=function(){switch(_typeof(this._val_)){case _TYPES.ARRAY:return this._val_;break;default:return[];break;}};_Model.prototype.child=function(attributeId__childIndex){switch(_typeof(this._val_)){case _TYPES.ARRAY:switch(_typeof(attributeId__childIndex)){case _TYPES.STRING:break;case _TYPES.NUMBER:return this._val_[attributeId__childIndex];break;}
break;default:if(_typeof(attributeId__childIndex)==_TYPES.STRING){return this[attributeId__childIndex];}
break;}};_Model.API=_API();return _Model;})();ns.Model=(function(){var _ns=ns,_root=root,_TYPES={STRING:"string",NUMBER:"number",ARRAY:"array",FUNCTION:"function",OBJECT:"object",UNDEFINED:"undefined",NULL:"null"},_API={GET:"get",SET:"set",ADD:"add",REMOVE:"remove",CHILDREN:"children",RANK:"RANK"};function _typeof(){var s=typeof this.target,_TYPES={STRING:"string",NUMBER:"number",ARRAY:"array",FUNCTION:"function",OBJECT:"object",UNDEFINED:"undefined",NULL:"null"};if(s===_TYPES.OBJECT){if(this.target){if(typeof this.target.length===_TYPES.NUMBER&&!(this.target.propertyIsEnumerable('length'))&&typeof this.target.splice===_TYPES.FUNCTION){s=_TYPES.ARRAY;}}else{s=_TYPES.NULL;}}
return s;}
function _Model(initObjLit,childId,parent){utils.Evint.apply(this);this.constructor=_ns.Model;var _this=this,_childId=childId||_root.CONST.MODEL_DEFAULT_ID,_vals=[],_parent=parent||false;;function _makeNew(initItem,attrib,_valIndex){switch(true){case initItem instanceof _Model:case initItem instanceof _BoolObject:case initItem instanceof _StringObject:case initItem instanceof _ArrayObject:case initItem instanceof _FunctionObject:_this[attrib]=initItem;break;case initItem.constructor==String:case initItem.constructor==Number:_this[attrib]=new _StringObject(initItem,attrib,_valIndex);break;case initItem.constructor==Boolean:_this[attrib]=new _BoolObject(initItem,attrib,_valIndex);break;case initItem instanceof Array:_this[attrib]=new _ArrayObject(initItem,attrib,_valIndex);break;case initItem instanceof Function:_this[attrib]=new _FunctionObject(initItem,attrib,_valIndex);break;case initItem instanceof Object:_this[attrib]=new _Model(initItem,_childId);break;default:break;}
try{_this[attrib].RANK=_valIndex;}catch(err){debug.debug(initItem,attrib,_valIndex);debug.debug(err);}}
function _resetRank(_arry){for(var i=0;i<_arry.length;i++){var _obj;if(_arry[i].constructor===String){_obj=_this[_arry[i]];}else{_obj=_arry[i];}
if(typeof(obj)!=="undefined"){_obj.RANK=i;}}}
function _StringObject(initString,attrib,_valIndex){utils.Evint.apply(this);this.constructor=_StringObject;var _thisString=this,_val,_attrib=attrib;_thisString.set=function(val){switch(_typeof(val)){case _TYPES.OBJECT:case _TYPES.ARRAY:case _TYPES.FUNCTION:case _TYPES.BOOLEAN:_makeNew(val,_attrib,_valIndex);return true;break;}
_val=val;_this.fire(_ns.CONST.EVENTS.CHANGE);return true;};_thisString.get=function(){return _val||"";};_thisString.set(initString);return _thisString;}
function _BoolObject(initBool,attrib,_valIndex){utils.Evint.apply(this);this.constructor=_BoolObject;var _thisBool=this,_val,_attrib=attrib;_thisBool.set=function(val){if(val.constructor!==Boolean){_makeNew(val,_attrib,_valIndex);return true;}
_val=val;_this.fire(_ns.CONST.EVENTS.CHANGE);return true;};_thisBool.get=function(){return _val;};_thisBool.set(initBool);return _thisBool;}
function _ArrayObject(initArray,attrib,_valIndex){utils.Evint.apply(this);this.constructor=_ArrayObject;var _thisArray=this,_children=[],_isIded,_attrib=attrib;_thisArray.set=function(arry){if(arry.constructor!==Array){_makeNew(arry,_attrib,_valIndex);return true;}
if((_children.length>0)&&(_isIded==true)){for(var i=0;i<_children.length;i++){_thisArray.remove(i);}}
_children=[];_isIded=false;for(var i=0;i<arry.length;i++){_thisArray.add(arry[i]);}
_this.fire(_ns.CONST.EVENTS.CHANGE);return true;};_thisArray.children=function(){return _children||[];};_thisArray.get=function(){var _returnArry=[];var _arry=_children;for(var i=0;i<_arry.length;i++){_returnArry.push(_arry[i].get());}
return _returnArry||[];};_thisArray.add=function(newMember){var _child=new _Model(newMember,_childId);_child.RANK=_children.length;_children.push(_child);if(_child[_childId]){_isIded=true;_thisArray[_child[_childId].get()]=_child;}
_this.fire(_ns.CONST.EVENTS.CHANGE);};_thisArray.remove=function(indexOrId){switch(indexOrId.constructor){case Number:if(_children[indexOrId][_childId]){delete _thisArray[_children[indexOrId][_childId].get()];}
var _removed=_children.splice(indexOrId,1);_resetRank(_children);return _removed;break;case String:var _index=_thisArray[indexOrId].RANK;delete _thisArray[indexOrId];var _removed=_children.splice(_index,1);_resetRank(_children);return _removed;break;default:return false;break;}
_this.fire(_ns.CONST.EVENTS.CHANGE);};_thisArray.set(initArray);return _thisArray;}
function _FunctionObject(initFunction,attrib,_valIndex){utils.Evint.apply(this);_this.constructor=_FunctionObject;var _thisFunction=this,_val,_attrib=attrib;_thisFunction.set=function(val){if(val.constructor!==(Function)){_makeNew(val,_attrib,_valIndex);return true;}
_val=val;_this.fire(_ns.CONST.EVENTS.CHANGE);return true;};_thisFunction.get=function(){return _val();};_thisFunction.set(initFunction);return _thisFunction;}
_this.get=function(){if(_this["SELF"]){return _this["SELF"].get();}
var _retObj={};for(var i=0;i<_vals.length;i++){try{_retObj[_vals[i]]=_this[_vals[i]].get();}catch(err){debug.error(_vals[i],_this,err);}}
return _retObj;};_this.set=function(objLit){if(_vals.length>0){for(var i=0;i<_vals.length;i++){_this.remove(_vals[i]);}}
_this.add(objLit);};_this.add=function(objLit){var _protected=utils.Array(_API,utils.Evint.API).arrayify();switch(true){case objLit instanceof _Model:_this=objLit;return true;break;case objLit.constructor==String:case objLit.constructor==Number:case objLit.constructor==Boolean:case objLit instanceof Array:case objLit instanceof Function:_this=new _Model({"SELF":objLit});break;default:for(var attrib in objLit){if(objLit.hasOwnProperty(attrib)){if(_protected.indexOf(attrib)==-1){if(_this[attrib]){try{_this[attrib].set(objLit[attrib]);}catch(err){debug.debug(attrib,_this,"failed!",err);}}else{var _curIndex=_vals.length;_vals[_curIndex]=attrib;_makeNew(objLit[attrib],attrib,_curIndex);}}else{throw("you can't overwrite a property that's protected by the Array and Evint API");}}}
break;}};_this.remove=function(idOrArray){var _arry=(idOrArray.constructor===Array)?idOrArray:[idOrArray],_returnArray=[];function _remove(idStr){if(_this[idStr]){var _removed=_this[idStr],_removedFromArray=_vals.splice(_removed.rank,1);delete _this[idStr];_resetRank(_vals);return _removed;}}
for(var i=0;i<_arry.length;i++){_returnArray.push(_remove(_arry[i]));}
_this.fire(_ns.CONST.EVENTS.CHANGE);return _returnArray;};if(typeof(initObjLit)!=="undefined"){_this.set(initObjLit);}
return _this;}
return _Model;})();mvc.version="2.0";